MobileWeb/MobileWeb/Controllers/adminProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileWeb.ViewModels;
using MobileWebBLL.BLL;
using MobileWebBLL.Models;
using System.IO;

using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using System.Transactions;
using System.Web.Security;
using WebMatrix.WebData;

using MobileWeb.Filters;
using MobileWeb.Models;

namespace MobileWeb.Controllers
{
    [Authorize(Roles = "Administrator")]
    [InitializeSimpleMembership]
    public class adminProductController : Controller
    {
        //
        // GET: /adminProduct/

        MobileWebEntities webmob = new MobileWebEntities();
        public ProductBLL adProduct = new ProductBLL();
        public NhaSanXuatBLL nsxBLL = new NhaSanXuatBLL();
        public LoaiSanPhamBLL lspBLL = new LoaiSanPhamBLL();
        public HinhAnhBLL imgBLL = new HinhAnhBLL();

        public ActionResult Index()
        {
            //var products = webmob.SanPhams.Where(p => p.TrangThai ==1);
            //products.OrderBy(p => p.MaNSX);
            List<SanPham> products = adProduct.ShowListProduct();
            return View(products);
        }
        public ActionResult adminShowDetailProduct(int MaSP)
        {

            List<ChiTietSanPham> ctsp = adProduct.ShowDetailsProduct(MaSP);
            List<HinhAnh> img = imgBLL.GetHinhAnh(MaSP);
            ViewBag.img = img;
            return View(ctsp);
        }
        public ActionResult CreateProduct()
        {
            ViewModelAdminProducts CreateProduct = new ViewModelAdminProducts
            {

                loaisp = adProduct.GetListCategories(),
                nhasanxuat = adProduct.GetListCompany(),
                //hedieuhanh = adProduct.GetListOperationSystem()
            };
            ViewBag.lsp = lspBLL.ShowListLoaiSanPham();
            ViewBag.nsx = nsxBLL.ListNhaSanXuat();
            return View(CreateProduct);
        }
        public ActionResult CreateProductSubmit(SanPham SanPham, ChiTietSanPham ChiTietSanPham)
        {
            adProduct.CreateroductDAO(SanPham, ChiTietSanPham);
            var MaSP = adProduct.GetLastProduct().MaSP;
            return RedirectToAction("CreateProductImages", new { MaSP = MaSP });
        }

        /*public ActionResult CreateProduct()
        {
            ViewModelAdminProducts CreateProduct = new ViewModelAdminProducts
            {

                loaisp = adProduct.GetListCategories(),
                nhasanxuat = adProduct.GetListCompany(),
                //hedieuhanh = adProduct.GetListOperationSystem()
            };
            ViewBag.lsp = lspBLL.ShowListLoaiSanPham();
            ViewBag.nsx = nsxBLL.ListNhaSanXuat();
            return View(CreateProduct);
        }

        [HttpPost]
        public ActionResult CreateProduct(SanPham SanPham, ChiTietSanPham ChiTietSanPham)
        {
            adProduct.CreateroductDAO(SanPham, ChiTietSanPham);
            var MaSP = adProduct.GetLastProduct().MaSP;
            ViewModelAdminProducts CreateProduct = new ViewModelAdminProducts
            {

                loaisp = adProduct.GetListCategories(),
                nhasanxuat = adProduct.GetListCompany(),
                SanPham = SanPham,
                ChiTietSanPham = ChiTietSanPham
                //hedieuhanh = adProduct.GetListOperationSystem()
            };
            ViewBag.lsp = lspBLL.ShowListLoaiSanPham();
            ViewBag.nsx = nsxBLL.ListNhaSanXuat();
            return View(CreateProduct);
        }*/

        public ActionResult CreateProductImages(int MaSP)
        {
            List<HinhAnh> img = imgBLL.GetHinhAnh(MaSP);
            ViewBag.img = img;
            ViewBag.masp = MaSP;
            return View();
        }

        public ActionResult ShowEidtPruduct(int MaSP, int? Message)
        {
            int mess = Message ?? 0;
            if (mess != 0)
                ViewBag.Mess = "Cập nhật thành công!!";
            List<HinhAnh> img = imgBLL.GetHinhAnh(MaSP);
            ViewBag.img = img;
            ViewBag.lsp = lspBLL.ShowListLoaiSanPham();
            ViewBag.nsx = nsxBLL.ListNhaSanXuat();
            ViewModelAdminProducts editProduct = new ViewModelAdminProducts
            {
                SanPham = adProduct.GetOneProduct(MaSP),
                ChiTietSanPham = adProduct.ShowDetailProduct(MaSP),
                loaisp = adProduct.GetListCategories(),
                nhasanxuat = adProduct.GetListCompany(),
                HinhAnh = new HinhAnh { MaSP = MaSP }
                //hedieuhanh = adProduct.GetListOperationSystem()
            };
            return View(editProduct);
        }

        public ActionResult EditProduct(SanPham SanPham, ChiTietSanPham ChiTietSanPham)
        {
            adProduct.EditProductDAO(SanPham, ChiTietSanPham);

            return RedirectToAction("ShowEidtPruduct", new { MaSP = SanPham.MaSP, Message = 1 });
        }

        [HttpPost]
        public ActionResult InsertHinh(HinhAnh HinhAnh, HttpPostedFileBase linkhinh)
        {
            if (linkhinh != null)
            {
                string filePath = Path.Combine(Server.MapPath("~/Images/home/mobiles/"), Path.GetFileName(linkhinh.FileName));

                linkhinh.SaveAs(filePath);
                HinhAnh.Link = linkhinh.FileName;
                imgBLL.InsertHinh(HinhAnh);
                return RedirectToAction("ShowEidtPruduct", new { MaSP = HinhAnh.MaSP });
            }
            else
            {
                return RedirectToAction("Index");
            }

            //Link.SaveAs(absFileAndPath);
            //return RedirectToAction("CreateProduct");
        }

        public ActionResult DeleteHinh(int MaHinhAnh, int MaSP)
        {
            imgBLL.DeleteHinh(MaHinhAnh);
            return RedirectToAction("ShowEidtPruduct", new { MaSP = MaSP });
        }

        public ActionResult DeleteProduct(int MaSP)
        {
            adProduct.DeleteProductDAO(MaSP);
            return RedirectToAction("Index");
        }

        public ActionResult LoadUploadHinh(int MaSP)
        {
            List<HinhAnh> img = imgBLL.GetHinhAnh(MaSP);
            ViewBag.img = img;
            ViewBag.lsp = lspBLL.ShowListLoaiSanPham();
            ViewBag.nsx = nsxBLL.ListNhaSanXuat();
            ViewModelAdminProducts editProduct = new ViewModelAdminProducts
            {
                SanPham = adProduct.GetOneProduct(MaSP),
                ChiTietSanPham = adProduct.ShowDetailProduct(MaSP),
                loaisp = adProduct.GetListCategories(),
                nhasanxuat = adProduct.GetListCompany(),
                HinhAnh = new HinhAnh { MaSP = MaSP }
                //hedieuhanh = adProduct.GetListOperationSystem()
            };
            return PartialView("_PartialUploadAnh", editProduct);
        }
        
    }
}

MobileWeb/MobileWeb/Views/adminProduct/CreateProductImages.cshtml
@model MobileWeb.ViewModels.ViewModelAdminProducts
@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin sản phẩm", "Index", "adminProduct", null, new { id = "returnListProduct" })
            <span class="divider">/</span>
        </li>
        <li>
            <span>Thêm sản phẩm</span>
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Thông tin sản phẩm</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
            </div>
        </div>
        <div class="box-content">
            <div class="control-group">
                <div class="control-label">
                    @Html.Label("", "Hình ảnh")
                </div>
                <div class="controls">
                    <div class="portfolio_1_4">
                        <ul id="list">
                            @foreach (var i in ViewBag.img)
                            {
                                <li class="app">
                                    <span class="image" style="position: relative">
                                        <a href="#" data-rel="prettyPhoto" class="img-thumb">
                                            <img class="portfolio_image" src="~/@Url.Content(i.Link)" alt="" /></a>
                                        <a onclick="return confirm('Bạn có chắc chắn muốn xóa');" href="@Url.Action("DeleteHinh", new { @MaHinhAnh = i.MaHinhAnh, @MaSP = i.MaSP })" class="button red">
                                            <i class="icon-trash icon-white"></i>
                                            Delete
                                        </a>
                                    </span>
                                </li>
                            }
                        </ul>
                    </div>

                </div>

            </div>


            @using (Html.BeginForm("InsertHinh", "adminProduct", FormMethod.Post, new { enctype = "multipart/form-data", @class = "insert_form" }))
                    {
                    
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Chọn đường dẫn")
                            </div>
                            <div class="controls">
                                <div class="uploader">
                                    <input name="linkhinh" type="file" class="input-file uniform_on" />
                                    @Html.Hidden("MaSP", new { @ViewBag.MaSP });
                                </div>
                                <a href="javascript:void(0);" class="btn btn-primary" onclick="$('.insert_form').submit();">Thêm Hình</a>
                                @*<button type="submit" class="btn btn-primary">Thêm Hình</button>*@
                            </div>
                        </div>                    
                    }

        </div>
        <!--/span-->
    </div>
    <!--/row-->
    <!-- content ends -->

MobileWeb/MobileWeb/Views/adminProduct/Index.cshtml
@model List<MobileWebBLL.Models.SanPham>
@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin sản phẩm", "Index", "adminProduct", null, new { id = "returnListProduct" })
        </li>
    </ul>
</div>


<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2>Sản phẩm</h2>
            <div class="box-icon">
                <div class="btn btn-success">
                    @Html.ActionLink("Create", "CreateProduct", "adminProduct", null, new { id = "btnCreateProduct" })
                </div>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable" id="ListProduct">
                <thead>
                    <tr>
                        <th>Tên sản phẩm</th>
                        <th>Loại sản phẩm</th>
                        <th>Nhà sản xuất</th>
                        <th>Số lượng</th>
                        <th>Đơn giá</th>
                        <th>Số lượt xem</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count == 0)
                    {
                        <tr>
                            <td colspan="8"><span>Không có thông tin cần hiển thị</span></td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                        <tr>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.TenSP)</td>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.LoaiSanPham.TenLoaiSP)</td>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.NhaSanXuat.TenNSX)</td>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.SoLuong)</td>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.DonGia)</td>
                            <td class="center">@Html.DisplayFor(Itemproduct => item.SoLuotXem)</td>
                            <td class="center">
                                <a class="btn btn-success" href="@Url.Action("adminShowDetailProduct", new { @MaSP = item.MaSP})">
                                    <i class="icon-zoom-in icon-white"></i>
                                </a>
                                <a class="btn btn-info" href="@Url.Action("ShowEidtPruduct", new { @MaSP = item.MaSP })">
                                    <i class="icon-edit icon-white"></i>
                                </a>
                                <a class="btn btn-danger" href="@Url.Action("DeleteProduct", new { @MaSP = item.MaSP})">
                                    <i class="icon-trash icon-white"></i>
                                </a>
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminProduct/_PartialUploadAnh.cshtml
@model MobileWeb.ViewModels.ViewModelAdminProducts
@{
    ViewBag.Title = "Cập nhật thông tin sản phẩm";
}

<div class="control-group">
    <div class="control-label">
        @Html.Label("", "Hình ảnh")
    </div>
    <div class="controls">
        <div class="portfolio_1_4">
            <ul id="list">
                @foreach (var i in ViewBag.img)
                {
                    <li class="app">
                        <span class="image" style="position: relative">
                            <a href="#" data-rel="prettyPhoto" class="img-thumb">
                                <img class="portfolio_image" src="~/@Url.Content(i.Link)" alt="" /></a>
                            <a onclick="return confirm('Bạn có chắc chắn muốn xóa');" href="@Url.Action("DeleteHinh", new { @MaHinhAnh = i.MaHinhAnh, @MaSP = i.MaSP })" class="button red">
                                <i class="icon-trash icon-white"></i>
                                Delete
                            </a>
                        </span>
                    </li>
                }
            </ul>
        </div>

    </div>

</div>@*Het hien thi hinh*@