MobileWeb/MobileWeb/Controllers/adminHoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using MobileWeb.ViewModels;
using MobileWebBLL.BLL;
using MobileWebBLL.Models;

namespace MobileWeb.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class adminHoaDonController : Controller
    {
        //
        // GET: /adminHoaDon/
        public HoaDonBLL adHoaDon = new HoaDonBLL();
        public ChiTietHoaDonBLL adcthd = new ChiTietHoaDonBLL();
        public KhachHangBLL adkhachhang = new KhachHangBLL();

        private void SendMail(long MaHD)
        {
            HoaDon hd = adHoaDon.GetOneBillToEdit(MaHD);
            int MaKH = int.Parse(hd.MaKH.ToString());
            KhachHang kh = adkhachhang.GetOneCustomer(MaKH);

            List<ChiTietHoaDon> listcthd = adcthd.ShowDetailsBill(MaHD);
            //Send mail
            MailMessage mail = new MailMessage();
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com", 587);
            mail.From = new MailAddress("tinivippromobile@gmail.com");
            mail.To.Add("violet.glass9x86@gmail.com");
            //mail.To.Add(kh.Email);
            mail.Subject = "Thông tin hóa đơn - TiniVippro";
            mail.IsBodyHtml = true;
            mail.Body += String.Format("Họ tên: <b>{0}</b><br/>Email: <b>{1}</b><br/>Ngày đặt hàng: <b>{2}</b><br/><br/>", kh.TenKH, kh.Email, String.Format("{0:dd/MM/yyyy}", hd.ThoiGianDatHang));
            for (int i = 0; i < listcthd.Count; i++)
            {
                mail.Body += String.Format("<span style=\"margin-left:20px\">+ Sản phẩm: </span><b>{0}</b> Số lượng: <b>{1}</b>        Thành tiền: <b>{2}</b><br/><br/>", listcthd[i].SanPham.TenSP, listcthd[i].SoLuong, listcthd[i].ThanhTien);
            }
            mail.Body += String.Format("Tổng tiền: <b>{0}</b>", hd.TongTien);
            SmtpServer.EnableSsl = true;
            SmtpServer.UseDefaultCredentials = false;
            var loginInfo = new System.Net.NetworkCredential("tinivippromobile@gmail.com", "tinivippro123");
            SmtpServer.Credentials = loginInfo;
            SmtpServer.Send(mail);
        }

        private void SendMailCancel(long MaHD)
        {
            HoaDon hd = adHoaDon.GetOneBillToEdit(MaHD);
            int MaKH = int.Parse(hd.MaKH.ToString());
            KhachHang kh = adkhachhang.GetOneCustomer(MaKH);

            List<ChiTietHoaDon> listcthd = adcthd.ShowDetailsBill(MaHD);
            //Send mail
            MailMessage mail = new MailMessage();
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com", 587);
            mail.From = new MailAddress("tinivippromobile@gmail.com");
            mail.To.Add("violet.glass9x86@gmail.com");
            //mail.To.Add(kh.Email);
            mail.Subject = "Thông báo hủy hóa đơn vì không thanh toán đúng kỳ hạn - TiniVippro";
            mail.IsBodyHtml = true;
            mail.Body += String.Format("Họ tên: <b>{0}</b><br/>Email: <b>{1}</b><br/>Ngày đặt hàng: <b>{2}</b><br/><br/>", kh.TenKH, kh.Email, String.Format("{0:dd/MM/yyyy}", hd.ThoiGianDatHang));
            for (int i = 0; i < listcthd.Count; i++)
            {
                mail.Body += String.Format("<span style=\"margin-left:20px\">+ Sản phẩm: </span><b>{0}</b> Số lượng: <b>{1}</b>        Thành tiền: <b>{2}</b><br/><br/>", listcthd[i].SanPham.TenSP, listcthd[i].SoLuong, listcthd[i].ThanhTien);
            }
            mail.Body += String.Format("Tổng tiền: <b>{0}</b>", hd.TongTien);
            SmtpServer.EnableSsl = true;
            SmtpServer.UseDefaultCredentials = false;
            var loginInfo = new System.Net.NetworkCredential("tinivippromobile@gmail.com", "tinivippro123");
            SmtpServer.Credentials = loginInfo;
            SmtpServer.Send(mail);
        }

        public ActionResult Index(int? ma)
        {
            int message = ma ?? 0;
            switch (message)
            {
                case 1: ViewBag.Message = "Cập nhật thành công"; break;
                case 2: ViewBag.Message = "Xóa thành công"; break;
                case 3: ViewBag.Message = "Xóa thất bại. Xin vui lòng thử lại sau"; break;
                case 4: ViewBag.Message = "Cập nhật thất bại. Xin vui lòng thử lại sau"; break;
                case 5: ViewBag.Message = "Hủy thành công"; break;
                case 6: ViewBag.Message = "Hủy thất bại. Xin vui lòng thử lại sau"; break;
            }
            var bills = adHoaDon.ShowListBills();
            return View(bills);
        }
        public ActionResult UpdateTinhTrang12(long MaHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.UpdateTinhTrangDAO12(MaHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 1 });
                SendMail(MaHD);
            }
            else
            {
                return RedirectToAction("Index", new { ma = 4 });
            }

        }

        public ActionResult UpdateTinhTrang3(long MaHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.UpdateTinhTrangDAO3(MaHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 1 });
            }
            else
            {
                return RedirectToAction("Index", new { ma = 4 });
            }
        }

        public ActionResult UpdateTinhTrang4(long MaHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.UpdateTinhTrangDAO4(MaHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 1 });
            }
            else
            {
                return RedirectToAction("Index", new { ma = 4 });
            }
        }

        public ActionResult ShowEditBill(long MaHD, int? ma)
        {
            int message = ma ?? 0;
            if (message == 10)
            {
                ViewBag.Message = "Cập nhật thất bại. Xin vui lòng thử lại sau";
            }
            var hd = adHoaDon.GetOneBillToEdit(MaHD);
            return View(hd);
        }

        public ActionResult EditBill(HoaDon HoaDon)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.UpdateBillDAO(HoaDon); if (kq)
            {
                return RedirectToAction("Index", new { ma = 1 });
            }
            else
            {
                return RedirectToAction("ShowEditBill", new { MaHD = HoaDon.MaHD, ma = 10 });
            }

        }

        public ActionResult CancelBill(long MaHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.CancelBillDAO(MaHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 5 });
            }
            else
            {
                return RedirectToAction("Index", new { ma = 6 });
            }
        }

        public ActionResult CancelBillOverdue()
        {
            bool kq = false;

            ViewBag.Message = null;
            List<HoaDon> listhd = adHoaDon.GetBillOverdue();
            kq = adHoaDon.CancelBillOverdue();
            for (int i = 0; i < listhd.Count; i++)
            {
                long MaHD = listhd[i].MaHD;
                SendMailCancel(MaHD);
            }
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 5 });
            }
            else
            {
                return RedirectToAction("Index", new { ma = 6 });
            }
        }

        public ActionResult adminShowListBillCancel(int? ma)
        {
            int message = ma ?? 0;
            if (message == 3)
            {
                ViewBag.Message = "Xóa thất bại. Xin vui lòng thử lại sau";
            }
            var bills = adHoaDon.ShowListCancelBills();
            return View(bills);
        }

        public ActionResult Deletebill(long MaHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adHoaDon.DeleteBillDAO(MaHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 2 });
            }
            else
            {
                return RedirectToAction("adminShowListBillCancel", new { ma = 3 });
            }
        }

        //Chi tiết hóa đơn

        public ActionResult adminShowDetailBill(long MaHD)
        {
            var cthd = adcthd.ShowDetailsBill(MaHD);
            return View(cthd);
        }

        public ActionResult DeleteDetailbill(long MaCTHD)
        {
            bool kq = false;

            ViewBag.Message = null;
            kq = adcthd.DeleteDetailBillDAO(MaCTHD);
            if (kq)
            {
                return RedirectToAction("Index", new { ma = 2 });
            }
            else
            {
                return RedirectToAction("Index", new { ma = 3 });
            }
        }

    }
}

MobileWeb/MobileWeb/Views/adminHoaDon/Index.cshtml
@model List<MobileWebBLL.Models.HoaDon>
@{
    ViewBag.Title = "Thông tin hóa đơn";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin hóa đơn", "Index", "adminHoaDon", null, new { id = "returnListHoaDon" })
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2>Chi tiết hóa đơn</h2>
        </div>
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.Message
            </div>
        }
        <div class="box-content">
            <a class="btn btn-primary" data-rel ="tooltip" title="Xem thông tin các đơn hàng đã hủy" href="@Url.Action("adminShowListBillCancel")">
                Các đơn hàng đã hủy
            </a>
            <a class="btn btn-danger" data-rel ="tooltip" title="Hủy các đơn hàng chưa thanh toán sau 24 giờ kể từ khi đặt hàng" href="@Url.Action("CancelBillOverdue")">
                Hủy đơn hàng
            </a>

            <br />
            <br />
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Tên khách hàng</th>
                        <th>Điện thoại</th>
                        <th>Địa chỉ giao hàng</th>
                        <th>Thời gian đặt hàng</th>
                        <th>Hình thức giao hàng</th>
                        <th>Hình thức thanh toán</th>
                        <th>Tổng tiền</th>
                        <th>Tình trạng</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count == 0)
                    {
                        <tr>
                            <td colspan="8"><span>Không có thông tin cần hiển thị</span></td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                        <tr>
                            <td class="center">@Html.DisplayFor(Itembill => item.TenKHDat)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.DienThoai)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.DiaChiGiaoHang)</td>
                            <td class="center">@Html.DisplayFor(Itembill =>item.ThoiGianDatHang)</td>
                            @switch (item.HinhThucGiaoHang)
                            {
                                case 1: <td class="center">Giao hàng tận nơi</td>;break;
                                case 2: <td class="center">Tới nhận hàng</td>;break;
                            }
                            @switch (item.HinhThucThanhToan)
                            {
                                case 1: <td class="center">Thanh toán online</td>;break;
                                case 2: <td class="center">Thanh toán trực tiếp</td>;break;
                            }
                            <td class="center">@Html.DisplayFor(Itembill => item.TongTien)</td>
                            @switch (item.TinhTrang)
                            {
                                case 1: <td class="center">Chưa thanh toán
                                            <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật đã thanh toán" href="@Url.Action("UpdateTinhTrang12", new { @MaHD = item.MaHD })">
                                                <i class="icon-edit icon-white"></i>
                                            </a>
                                        </td>; break;
                                case 2: <td class="center">Đã thanh toán - chưa xác nhận - chưa giao hàng
                                                <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật đã thanh toán" href="@Url.Action("UpdateTinhTrang12", new { @MaHD = item.MaHD })">
                                                    <i class="icon-edit icon-white"></i>
                                                </a>
                                            </td>; break;
                                case 3: <td class="center">Đã xác nhận thanh toán - chưa giao hàng
                                                <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật đang giao hàng" href="@Url.Action("UpdateTinhTrang3", new { @MaHD = item.MaHD })">
                                                    <i class="icon-edit icon-white"></i>
                                                </a>
                                            </td>; break;
                                case 4: <td class="center">Đã xác nhận thanh toán - đang giao hàng
                                                    <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật đã giao hàng" href="@Url.Action("UpdateTinhTrang4", new { @MaHD = item.MaHD })">
                                                        <i class="icon-edit icon-white"></i>
                                                    </a>
                                                </td>; break;
                                case 5: <td class="center">Đã giao hàng</td>; break;
                            }
                            <td class="center">
                                <a class="btn btn-success" data-rel ="tooltip" title="Xem chi tiết" href="@Url.Action("adminShowDetailBill", new { @MaHD = item.MaHD})">
                                    <i class="icon-zoom-in icon-white"></i>
                                </a>
                                @if (item.TinhTrang == 1 || item.TinhTrang == 2 || item.TinhTrang == 3)
                                {
                                    <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật đơn hàng" href="@Url.Action("ShowEditBill", new { @MaHD = item.MaHD })">
                                        <i class="icon-edit icon-white"></i>
                                    </a>
                                    <a class="btn btn-warning" data-rel ="tooltip" title="Hủy đơn hàng" onclick="return confirm('Bạn có chắc chắn muốn hủy đơn hàng này');" href="@Url.Action("CancelBill", new { @MaHD = item.MaHD })">
                                        <i class="icon-trash icon-white"></i>
                                    </a>
                                }
                                @if(item.TinhTrang == 0)
                                {
                                    <a class="btn btn-danger" data-rel ="tooltip" title="Xóa đơn hàng" onclick="return confirm('Bạn có chắc chắn muốn xóa đơn hàng này');" href="@Url.Action("Deletebill", new { @MaHD = item.MaHD })">
                                        <i class="icon-trash icon-white"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminHoaDon/ShowEditBill.cshtml
@model MobileWebBLL.Models.HoaDon
@{
    ViewBag.Title = "Cập nhật thông tin đơn hàng";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin đơn hàng", "Index", "adminHoaDon", null, new { id = "returnListLoaiSP" })
            <span class="divider">/</span>
        </li>
        <li>
            <span>Cập nhật thông tin đơn hàng</span>
        </li>
    </ul>
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @ViewBag.Message
    </div>
}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Thông tin đơn hàng</h2>
        </div>
        <div class="box-content">
            <div class="form-horizontal">
                @using (Html.BeginForm("EditBill", "adminHoaDon", FormMethod.Post, new { id = "EditBill" }))
                {
                    <fieldset>
                        <div class="control-group">
                            <div class="controls">
                                @Html.HiddenFor(item => item.MaHD, new { @class = "input-xlarge focused" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tên khách hàng")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.TenKHDat, new { @class = "input-xlarge disabled", disabled = "" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Điện thoại")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.DienThoai, new { @class = "input-xlarge focused" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Địa chỉ giao hàng")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.DiaChiGiaoHang, new { @class = "input-xlarge focused" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Thời gian đặt hàng")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.ThoiGianDatHang, new { @class = "input-xlarge disabled", disabled = "" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Hình thức giao hàng")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.HinhThucGiaoHang, new { @class = "input-xlarge disabled", disabled = "" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Hình thức thanh toán")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.HinhThucThanhToan, new { @class = "input-xlarge disabled", disabled = "" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tổng tiền")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.TongTien, new { @class = "input-xlarge disabled", disabled = "" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-edit icon-white"></i>
                                Cập nhật đơn hàng
                            </button>
                            <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn hủy cập nhật');" href="@Url.Action("Index")">
                                <i class="icon-trash icon-white"></i>
                                Hủy bỏ cập nhật
                            </a>
                        </div>
                    </fieldset>
                }
            </div>

        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminHoaDon/adminShowDetailBill.cshtml
@model List<MobileWebBLL.Models.ChiTietHoaDon>
@{
    ViewBag.Title = "Thông tin chi tiết hóa đơn";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin hóa đơn", "Index", "adminHoaDon", null, new { id = "returnListHoaDon" })
            <span class="divider">/</span>
        </li>
        <li>
            <span>Quản lý thông tin chi tiết hóa đơn</span>
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2>Chi tiết hóa đơn</h2>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Mã hóa đơn</th>
                        <th>Sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Thành tiền</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count == 0)
                    {
                        <tr>
                            <td colspan="8"><span>Không có thông tin cần hiển thị</span></td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                        <tr>
                            <td class="center">@Html.DisplayFor(Itembill => item.MaHD)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.SanPham.TenSP)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.SoLuong)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.ThanhTien)</td>
                            <td class="center">
                                @if(item.HoaDon.TinhTrang == 1)
                                {
                                    <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa đơn hàng này');" href="@Url.Action("DeleteDetailbill", new { @MaCTHD = item.MaCTHD })">
                                        <i class="icon-trash icon-white"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminHoaDon/adminShowListBillCancel.cshtml
@model List<MobileWebBLL.Models.HoaDon>
@{
    ViewBag.Title = "Thông tin hóa đơn";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin hóa đơn", "Index", "adminHoaDon", null, new { id = "returnListHoaDon" })
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2>Đơn hàng đã hủy</h2>
        </div>
		@if (ViewBag.Message != null)
        {
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.Message
            </div>
        }
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Tên khách hàng</th>
                        <th>Điện thoại</th>
                        <th>Địa chỉ giao hàng</th>
                        <th>Thời gian đặt hàng</th>
                        <th>Tổng tiền</th>
                        <th>Tình trạng</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count == 0)
                    {
                        <tr>
                            <td colspan="8"><span>Không có thông tin cần hiển thị</span></td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                        <tr>
                            <td class="center">@Html.DisplayFor(Itembill => item.KhachHang.TenKH)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.DienThoai)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.DiaChiGiaoHang)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.ThoiGianDatHang)</td>
                            <td class="center">@Html.DisplayFor(Itembill => item.TongTien)</td>
                            @switch (item.TinhTrang)
                            {
                                case 0: <td class="center">Hủy</td>; break;
                            }
                            <td class="center">
                                <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa đơn hàng này');" href="@Url.Action("Deletebill", new { @MaHD = item.MaHD })">
                                    <i class="icon-trash icon-white"></i>
                                </a>
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->