MobileWeb/MobileWeb/Controllers/adminPersonalInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using MobileWeb.Filters;
using MobileWeb.ViewModels;
using MobileWebBLL.BLL;
using MobileWeb.Models;
using MobileWebBLL.Models;
using MobileWeb.App_Code;

namespace MobileWeb.Controllers
{

    [Authorize]
    [InitializeSimpleMembership]
    public class adminPersonalInfoController : Controller
    {
        //
        // GET: /adminPersonnalInfo/
        public NhanVienBLL adnhanvien = new NhanVienBLL();
        public UserProfileBLL aduser = new UserProfileBLL();

        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
        }

        public ActionResult Index(string username)
        {
            NhanVien nv = adnhanvien.GetOneEmployeeString(username);
            ViewModelAdminUpPersonalInfo nvp = new ViewModelAdminUpPersonalInfo
            {
                MaNV = nv.MaNV,
                TenNV = nv.TenNV,
                ChucVu = nv.ChucVu,
                Username = nv.UserProfile.UserName
            };
            return View(nvp);
        }

        // POST: /Account/LogOff

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            WebSecurity.Logout();

            return RedirectToAction("Login", "Account");
        }

        // GET: /Account/Manage

        public ActionResult ChangePass(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                : "";
            ViewBag.HasLocalPassword = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            ViewBag.ReturnUrl = Url.Action("ChangePass");
            return View();
        }

        //
        // POST: /Account/Manage

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePass(LocalPasswordModel model)
        {
            bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            ViewBag.HasLocalPassword = hasLocalAccount;
            ViewBag.ReturnUrl = Url.Action("ChangePass");
            if (hasLocalAccount)
            {
                if (ModelState.IsValid)
                {
                    // ChangePassword will throw an exception rather than return false in certain failure scenarios.
                    bool changePasswordSucceeded;
                    try
                    {
                        changePasswordSucceeded = WebSecurity.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword);
                    }
                    catch (Exception)
                    {
                        changePasswordSucceeded = false;
                    }

                    if (changePasswordSucceeded)
                    {
                        return RedirectToAction("ChangePass", new { Message = ManageMessageId.ChangePasswordSuccess });
                    }
                    else
                    {
                        ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
                    }
                }
            }
            else
            {
                // User does not have a local password so remove any validation errors caused by a missing
                // OldPassword field
                ModelState state = ModelState["OldPassword"];
                if (state != null)
                {
                    state.Errors.Clear();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        WebSecurity.CreateAccount(User.Identity.Name, model.NewPassword);
                        return RedirectToAction("Manage", new { Message = ManageMessageId.SetPasswordSuccess });
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e);
                    }
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }


    }
}

MobileWeb/MobileWeb/Views/adminPersonalInfo/ChangePass.cshtml
@model MobileWeb.Models.LocalPasswordModel
@{
    ViewBag.Title = "cập nhật mật khẩu";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<!-- content starts -->
<div>
    <ul class="breadcrumb">
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Cập nhật mật khẩu</h2>
        </div>
        <div class="box-content">
            <div class="form-horizontal">
                <hgroup class="title">
                    <h1>@ViewBag.Title.</h1>
                </hgroup>

                <p class="message-success">@ViewBag.StatusMessage</p>

                <p>You're logged in as <strong><i>@User.Identity.Name</i></strong>.</p>

                @if (ViewBag.HasLocalPassword)
                {
                    @Html.Partial("_adminChangePasswordPartial")
                }
                else
                { 
                    @Html.Partial("_adminSetPasswordPartial")
                }

                <section id="externalLogins">
                    @Html.Action("RemoveExternalLogins","Account")
                </section>

            </div>

        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminPersonalInfo/Index.cshtml
@model MobileWeb.ViewModels.ViewModelAdminUpPersonalInfo
@{
    ViewBag.Title = "Cập nhật thông tin cá nhân";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<!-- content starts -->
<div>
    <ul class="breadcrumb">
        
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Thông tin cá nhân</h2>
        </div>
        <div class="box-content">
            <div class="form-horizontal">
                @using (Html.BeginForm("EditEmployee", "adminNhanVien", FormMethod.Post, new { id = "EditNhanVien" }))
                {
                    
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    <fieldset>
                        <div class="control-group">
                            <div class="controls">
                                @Html.HiddenFor(item => item.MaNV, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.MaNV)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tên nhân viên")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.TenNV, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.TenNV)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tên đăng nhập")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.Username, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.Username)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "chức vụ")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.ChucVu, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.ChucVu)
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-edit icon-white"></i>
                                Cập nhật
                            </button>
                            <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn hủy cập nhật');" href="@Url.Action("Index")">
                                <i class="icon-trash icon-white"></i>
                                Hủy bỏ cập nhật
                            </a>
                        </div>
                    </fieldset>
                }
            </div>

        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminPersonalInfo/_adminChangePasswordPartial.cshtml
@model MobileWeb.Models.LocalPasswordModel


@using (Html.BeginForm("ChangePass", "adminPersonalInfo"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <fieldset>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.OldPassword)
            </div>
            <div class="controls">
                @Html.PasswordFor(m => m.OldPassword)
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.NewPassword)
            </div>
            <div class="controls">
                @Html.PasswordFor(m => m.NewPassword)
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.ConfirmPassword)
            </div>
            <div class="controls">
                @Html.PasswordFor(m => m.ConfirmPassword)
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                <i class="icon-edit icon-white"></i>
                Cập nhật mật khẩu
            </button>
            <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn hủy cập nhật');" href="@Url.Action("Index", "adminProduct")">
                <i class="icon-trash icon-white"></i>
                Hủy bỏ cập nhật
            </a>
        </div>
    </fieldset>
}

MobileWeb/MobileWeb/Views/adminPersonalInfo/_adminSetPasswordPartial.cshtml
@model MobileWeb.Models.LocalPasswordModel

<p>
    You do not have a local password for this site. Add a local
    password so you can log in without an external login.
</p>

@using (Html.BeginForm("ChangePass", "adminPersonalInfo"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <fieldset>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.NewPassword)
            </div>
            <div class="controls">
                @Html.PasswordFor(m => m.NewPassword)
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.ConfirmPassword)
            </div>
            <div class="controls">
                @Html.PasswordFor(m => m.ConfirmPassword)
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                <i class="icon-edit icon-white"></i>
                Cập nhật mật khẩu
            </button>
            <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn hủy cập nhật');" href="@Url.Action("Index", "adminProduct")">
                <i class="icon-trash icon-white"></i>
                Hủy bỏ cập nhật
            </a>
        </div>
    </fieldset>
}