MobileWeb/MobileWeb/Controllers/adminKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileWeb.ViewModels;
using MobileWebBLL.BLL;
using MobileWebBLL.Models;

using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using MobileWeb.Filters;
using MobileWeb.Models;

namespace MobileWeb.Controllers
{
    [Authorize(Roles = "Administrator")]
    [InitializeSimpleMembership]
    public class adminKhachHangController : Controller
    {
        //
        // GET: /adminKhachHang/
        public KhachHangBLL adkhachhang = new KhachHangBLL();
        public UserProfileBLL aduser = new UserProfileBLL();
        MobileWebEntities webmob = new MobileWebEntities();

        public ActionResult Index(int? ma)
        {
            int message = ma ?? 0;
            switch (message)
            {
                case 1: ViewBag.Message = "Cập nhật thành công"; break;
                case 2: ViewBag.Message = "Xóa thành công"; break;
                case 3: ViewBag.Message = "Xóa thất bại. Xin vui lòng thử lại sau"; break;
            }
            List<KhachHang> kh = adkhachhang.GetListCustomer();
            return View(kh);
        }

        public ActionResult ShowEditCustomer(int MaKH, int? ma)
        {
            int message = ma ?? 0;
            if (message == 10)
            {
                ViewBag.Message = "Cập nhật thất bại. Xin vui lòng thử lại sau";
            }
            KhachHang kh = adkhachhang.GetOneCustomer(MaKH);
            ViewModelCustomerInfo khp = new ViewModelCustomerInfo
            {
                MaKH = kh.MaKH,
                TenKH = kh.TenKH,
                Username = kh.UserProfile.UserName,
                DiaChi = kh.DiaChi,
                Email = kh.Email,
                DienThoai = kh.DienThoai
            };
            return View(khp);
        }

        public ActionResult EditCustomer(ViewModelCustomerInfo ViewModelCustomerInfo)
        {
            bool kq = false;
            ViewBag.Message = null;
            KhachHang kh = adkhachhang.GetOneCustomer(ViewModelCustomerInfo.MaKH);
            kh.TenKH = ViewModelCustomerInfo.TenKH;
            kh.DiaChi = ViewModelCustomerInfo.DiaChi;
            kh.UserProfile.UserName = ViewModelCustomerInfo.Username;
            kh.DienThoai = ViewModelCustomerInfo.DienThoai;
            kh.Email = ViewModelCustomerInfo.Email;
            kq = adkhachhang.UpdateCustomer(kh);

            if (kq)
            {
                return RedirectToAction("Index", new { ma = 1 });
            }
            else
            {
                return RedirectToAction("ShowEditCustomer", new { MaKH = ViewModelCustomerInfo.MaKH, ma = 10 });
            }
        }

        
        public ActionResult DeleteCustomer(int MaKH, string UserName)
        {
            bool kq = false;
            ViewBag.Message = null;
                // TODO: Add delete logic here
                KhachHang kh = adkhachhang.GetOneCustomer(MaKH);
                int userid = int.Parse(kh.UserId.ToString());
                kq = adkhachhang.DeleteCustomer(MaKH);
                Roles.RemoveUserFromRole(UserName, "Administrator");
                Membership.DeleteUser(UserName);

                if (kq)
                {
                    return RedirectToAction("Index", new { ma = 2 });
                }
                else
                {
                    return RedirectToAction("Index", new { ma = 3 });
                }
        }
    }
}

MobileWeb/MobileWeb/Views/adminKhachHang/Index.cshtml
@model List<MobileWebBLL.Models.KhachHang>
@{
    ViewBag.Title = "Danh sách khách hàng";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin khách hàng", "Index", "adminKhachHang", null, new { id = "returnListKhachHang" })
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2>Khách hàng</h2>
        </div>
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.Message
            </div>
        }
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable" id="ListCustomer">
                <thead>
                    <tr>
                        <th>Tên khách hàng</th>
                        <th>Username</th>
                        <th>Địa chỉ</th>
                        <th>Email</th>
                        <th>Điện thoại</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count == 0)
                    {
                        <tr>
                            <td colspan="8"><span>Không có thông tin cần hiển thị</span></td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                        <tr>
                            <td class="center">@Html.DisplayFor(Itemcustomer => item.TenKH)</td>
                            <td class="center">@Html.DisplayFor(Itemcustomer => item.UserProfile.UserName)</td>
                            <td class="center">@Html.DisplayFor(Itemcustomer => item.DiaChi)</td>
                            <td class="center">@Html.DisplayFor(Itemcustomer => item.Email)</td>
                            <td class="center">@Html.DisplayFor(Itemcustomer => item.DienThoai)</td>
                            <td class="center">
                                <a class="btn btn-info" data-rel ="tooltip" title="Cập nhật thông tin" href="@Url.Action("ShowEditCustomer", new { @MaKH = item.MaKH })">
                                    <i class="icon-edit icon-white"></i>
                                </a>
                                <a class="btn btn-danger" data-rel ="tooltip" title="Xóa khách hàng" onclick="return confirm('Bạn có chắc chắn muốn xóa khách hàng này');" href="@Url.Action("DeleteCustomer", new {@MaKH = item.MaKH, @UserName = item.UserProfile.UserName})">
                                    <i class="icon-trash icon-white"></i>
                                </a>
                            </td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->

MobileWeb/MobileWeb/Views/adminKhachHang/ShowEditCustomer.cshtml
@model MobileWeb.ViewModels.ViewModelCustomerInfo
@{
    ViewBag.Title = "ShowEditCustomer";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            @Html.ActionLink("Quản lý thông tin khách hàng", "Index", "adminKhachHang", null, new { id = "returnListKhachHang" })
            <span class="divider">/</span>
        </li>
        <li>
            <span>Sửa thông tin Khách hàng</span>
        </li>
    </ul>
</div>

@if (ViewBag.Message != null)
{
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @ViewBag.Message
    </div>
}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Thông tin khách hàng</h2>
        </div>
        <div class="box-content">
            <div class="form-horizontal">
                @using (Html.BeginForm("EditCustomer", "adminKhachHang", FormMethod.Post, new { id = "EditKhachHang" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    <fieldset>
                        <div class="control-group">
                            <div class="controls">
                                @Html.HiddenFor(item => item.MaKH, new { @class = "input-xlarge focused" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tên khách hàng")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.TenKH, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.TenKH)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Tên đăng nhập")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.Username, new { @class = "input-xlarge focused", disable = "" })
                                @Html.ValidationMessageFor(item => item.TenKH)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Địa chỉ")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.DiaChi, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.DiaChi)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Email")
                            </div>
                            <div class="controls">
                                @Html.TextBoxFor(item => item.Email, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.Email)
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="control-label">
                                @Html.Label("", "Điện thoại")
                            </div>
                            <div class="controls">
                                @Html.TextAreaFor(item => item.DienThoai, new { @class = "input-xlarge focused" })
                                @Html.ValidationMessageFor(item => item.DienThoai)
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-edit icon-white"></i>
                                Cập nhật khách hàng
                            </button>
                            <a class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn hủy cập nhật');" href="@Url.Action("Index")">
                                <i class="icon-trash icon-white"></i>
                                Hủy bỏ cập nhật
                            </a>
                        </div>
                    </fieldset>
                }
            </div>

        </div>
    </div>
    <!--/span-->
</div>
<!--/row-->
<!-- content ends -->